#############################################################################
# Makefile for building: platformer
# Generated by qmake (2.01a) (Qt 4.8.2) on: Tue Mar 11 23:25:42 2014
# Project:  ../platformer/platformer.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../platformer/platformer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I../platformer -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -I. -I../platformer -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib \-lGLU -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../platformer/main.cpp \
		../platformer/mainwindow.cpp \
		../platformer/view.cpp \
		../platformer/obj.cpp \
		../platformer/camera.cpp \
		../platformer/scene.cpp \
		../platformer/player.cpp moc_mainwindow.cpp \
		moc_view.cpp \
		qrc_source.cpp
OBJECTS       = main.o \
		mainwindow.o \
		view.o \
		obj.o \
		camera.o \
		scene.o \
		player.o \
		moc_mainwindow.o \
		moc_view.o \
		qrc_source.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		../platformer/platformer.pro
QMAKE_TARGET  = platformer
DESTDIR       = 
TARGET        = platformer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ../platformer/platformer.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../platformer/platformer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../platformer/platformer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/platformer1.0.0 || $(MKDIR) .tmp/platformer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/platformer1.0.0/ && $(COPY_FILE) --parents ../platformer/mainwindow.h ../platformer/view.h ../platformer/vector.h ../platformer/obj.h ../platformer/camera.h ../platformer/scene.h ../platformer/player.h .tmp/platformer1.0.0/ && $(COPY_FILE) --parents ../platformer/source.qrc .tmp/platformer1.0.0/ && $(COPY_FILE) --parents ../platformer/main.cpp ../platformer/mainwindow.cpp ../platformer/view.cpp ../platformer/obj.cpp ../platformer/camera.cpp ../platformer/scene.cpp ../platformer/player.cpp .tmp/platformer1.0.0/ && $(COPY_FILE) --parents ../platformer/mainwindow.ui .tmp/platformer1.0.0/ && (cd `dirname .tmp/platformer1.0.0` && $(TAR) platformer1.0.0.tar platformer1.0.0 && $(COMPRESS) platformer1.0.0.tar) && $(MOVE) `dirname .tmp/platformer1.0.0`/platformer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/platformer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_view.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_view.cpp
moc_mainwindow.cpp: ../platformer/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../platformer/mainwindow.h -o moc_mainwindow.cpp

moc_view.cpp: ../platformer/camera.h \
		../platformer/vector.h \
		../platformer/scene.h \
		../platformer/obj.h \
		../platformer/player.h \
		../platformer/view.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ../platformer/view.h -o moc_view.cpp

compiler_rcc_make_all: qrc_source.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_source.cpp
qrc_source.cpp: ../platformer/source.qrc \
		../platformer/level_easy_navmesh.obj \
		../platformer/level_island_navmesh.obj \
		../platformer/level_easy.obj \
		../platformer/level_island.obj \
		../platformer/level_hard.obj \
		../platformer/level_easy.png \
		../platformer/level_hard.png \
		../platformer/level_hard_channels.png \
		../platformer/level_island_channels.png \
		../platformer/level_island.png \
		../platformer/level_easy_channels.png
	/usr/bin/rcc -name source ../platformer/source.qrc -o qrc_source.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: ../platformer/mainwindow.ui \
		../platformer/view.h \
		../platformer/camera.h \
		../platformer/vector.h \
		../platformer/scene.h \
		../platformer/obj.h \
		../platformer/player.h
	/usr/bin/uic-qt4 ../platformer/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: ../platformer/main.cpp ../platformer/mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../platformer/main.cpp

mainwindow.o: ../platformer/mainwindow.cpp ../platformer/mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o ../platformer/mainwindow.cpp

view.o: ../platformer/view.cpp ../platformer/view.h \
		../platformer/camera.h \
		../platformer/vector.h \
		../platformer/scene.h \
		../platformer/obj.h \
		../platformer/player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ../platformer/view.cpp

obj.o: ../platformer/obj.cpp ../platformer/obj.h \
		../platformer/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj.o ../platformer/obj.cpp

camera.o: ../platformer/camera.cpp ../platformer/camera.h \
		../platformer/vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o ../platformer/camera.cpp

scene.o: ../platformer/scene.cpp ../platformer/scene.h \
		../platformer/vector.h \
		../platformer/obj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scene.o ../platformer/scene.cpp

player.o: ../platformer/player.cpp ../platformer/player.h \
		../platformer/vector.h \
		../platformer/scene.h \
		../platformer/obj.h \
		../platformer/camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o ../platformer/player.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_view.o: moc_view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_view.o moc_view.cpp

qrc_source.o: qrc_source.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_source.o qrc_source.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

