#ifndef COMMON_H
#define COMMON_H

enum Command {IGNORE, CONTINUE, STOP, F, f, YAW, NEGYAW, PITCH, NEGPITCH, ROLL, NEGROLL, LINEWIDTH, COLOR, POP, PUSH};

enum Operation {ADD, EXPONENT, SUBTRACT, DIVIDE, MULTIPLY};

#endif // COMMON_H
